# This file is covered by the LICENSE file in the root of this project.
labels: 
  0 : "unlabeled"
  1 : "building"
  2: "fences"
  3: "other"
  4: "pedestrian"
  5: "pole"
  6: "road-lines"
  7: "road"
  8: "sidewalk"
  9: "vegetation"
  10: "vehicle"
  11: "wall"
  12: "traffic-sign"
  13: "sky"
  14: "other-ground"
  15: "bridge"
  16: "rail-track"
  17: "guard-rail"
  18: "traffic-light"
  19: "static"
  20: "dynamic"
  21: "water"
  22: "terrain"
  23: "extra-1"
  24: "extra-2"


color_map: # bgr sjy TODO
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  2: [245, 150, 100]
  3: [245, 230, 100]
  4: [250, 80, 100]
  5: [150, 60, 30]
  6: [255, 0, 0]
  7: [180, 30, 80]
  8: [255, 0, 0]
  9: [30, 30, 255]
  10: [200, 40, 255]
  11: [90, 30, 150]
  12: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]

# we should be able to not modify this
content: # as a ratio with the total number of points sjy TODO
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  11: 0.00016609538710764618
  13: 2.7879693665067774e-05
  15: 0.00039838616015114444
  16: 0.0
  18: 0.0020633612104619787
  20: 0.0016218197275284021
  30: 0.00017698551338515307
  31: 1.1065903904919655e-08
  32: 5.532951952459828e-09
  40: 0.1987493871255525
  44: 0.014717169549888214
  48: 0.14392298360372
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  52: 0.002395131480328884
  60: 4.7084144280367186e-05
  70: 0.26681502148037506
  71: 0.006035012012626033
  72: 0.07814222006271769
  80: 0.002855498193863172
  81: 0.0006155958086189918
  99: 0.009923127583046915
  252: 0.001789309418528068
  253: 0.00012709999297008662
  254: 0.00016059776092534436
  255: 3.745553104802113e-05
  256: 0.0
  257: 0.00011351574470342043
  258: 0.00010157861367183268
  259: 4.3840131989471124e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent

# Validation per class iou: 
# building : 14.41%
# fences : 7.74%
# pedestrian : 81.88%
# pole : 82.29%
# road-lines : 0.05%
# road : 95.13%
# sidewalk : 17.87%
# vegetation : 72.55%
# vehicle : 99.63%
# wall : 33.85%
# traffic-sign : 41.90%
# sky : 0.00%
# ground : 15.96%
# bridge : 0.00%
# rail-track : 0.00%
# guard-rail : 63.17%
# traffic-light : 0.00%
# static : 0.27%
# dynamic : 4.21%
# water : 0.00%
# terrain : 3.29%
# Current val miou is 30.199 while the best val miou is 31.677
# Current val loss is 2.503

learning_map: # ignore the 
  0 : 0     # "unlabeled"
  1 : 1     # "building"
  2 : 2     # "fence"
  3 : 0     # "other" mapped to "unlabeled" --------------------------mapped
  4 : 3     # "pedestrian"
  5 : 4     # "pole"
  6 : 5     # "roadline" mapped to "road" --------------------------mapped
  7 : 5     # "road"
  8 : 6     # "sidewalk"
  9 : 7     # "vegetation"
  10: 8     # "vehicles"
  11: 0     # "wall" mapped to "unlabeled" --------------------------mapped
  12: 9    # "traffic-sign"
  13: 0    # "sky" mapped to "unlabeled" --------------------------mapped
  14: 0    # "other-ground" mapped to "unlabeled" --------------------------mapped
  15: 0    # "bridge" mapped to "unlabeled" --------------------------mapped
  16: 0    # "rail-track" mapped to "unlabeled" --------------------------mapped
  17: 9     # "guard-rail"
  18: 0     # "traffic-light" mapped to "unlabeled" --------------------------mapped
  19: 0    # "static" mapped to "unlabeled" --------------------------mapped
  20: 0    # "dynamic" mapped to "unlabeled" --------------------------mapped
  21: 0    # "water" mapped to "unlabeled" --------------------------mapped
  22: 10    # "terrain"
  23: 0    # "extra-1" mapped to "unlabeled" --------------------------mapped
  24: 0     # "extra-2" mapped to "unlabeled" --------------------------mapped

learning_map_inv: # inverse of previous map
  0 : 0     # "unlabeled"
  1 : 1     # "building"
  2: 2     # "fence"
  3: 4     # "pedestrian"
  4: 5     # "pole"
  5: 7     # "road"
  6: 8     # "sidewalk"
  7: 9     # "vegetation"
  8: 10     # "vehicles"
  9: 17     # "traffic-sign"
  10: 22     # "terrain"
  # 11: 12     # "road"
  # 12: 13    # "parking"
  # 13: 14    # "sidewalk"
  # 14: 15    # "other-ground"
  # 15: 16    # "building"
  # 16: 17    # "fence"
  # 17: 18     # "other-structure" mapped to "unlabeled" ------------------mapped
  # 18: 19     # "lane-marking" to "road" ---------------------------------mapped
  # 19: 20    # "vegetation"
  # 20: 21    # "trunk"
  # 21: 22    # "terrain"
  # 23: 23    # "traffic-sign"
  # 24: 24     # "other-object" to "unlabeled" ----------------------------mapped

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  # 11: False    # "sidewalk"
  # 12: False    # "other-ground"
  # 13: False    # "building"
  # 14: False    # "fence"
  # 15: False    # "vegetation"
  # 16: False    # "trunk"
  # 17: False    # "terrain"
  # 18: True    # "pole"
  # 19: True    # "traffic-sign"
  # 20: False    # "vegetation"
  # 21: False    # "trunk"
  # 23: True    # "pole"
  # 24: True    # "traffic-sign"

split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17


  valid:
    - 18
    - 19
    - 20
  test:
    - 21
    - 22
    - 23
